watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start"
bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 200
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: true
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "home",          
          "cpu",
          "memory",
          "wifi",
          "taskbar",
        ]
      center:
        [
        "active_window",
        "weather"
        ]
      right:
        [
          "windows_workspaces",
          "clock",
          "bluetooth", 
          "volume",
          "battery",
          "power_menu"
        ]
widgets:
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf43a</span>{%I:%M %p}"
      label_alt: "{%a, %d %b %H:%M:%S}"
      locale: "en_US" # Language for date, you can set your own, example fr_FR
      timezones: [] #Looking up time zone info from registry
      callbacks:
        on_middle: "next_timezone"
        on_right: "exec cmd.exe /c start ms-clock:"
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        show_holidays: true
        show_week_numbers: true
        country_code: "US"
        holiday_color: "#FF6464"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "<span>{icon}</span> {location}: {temp}, Min {min_temp}, Max {max_temp}, Wind {wind}"
      api_key: "24b6c2cda6d84066b0304531241908" # Get your free API key from https://www.weatherapi.com/
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: "Overland Park, Kansas" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      units: "imperial"
      callbacks:
        on_left: "toggle_card"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start msnweather:"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue312"
        cloudyNight: "\ue311"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyIcyDay: "\ue30a"
        snowyIcyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
      weather_card:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        icon_size: 64
        show_hourly_forecast: true # Set to False to disable hourly forecast
        time_format: "24h" # can be 12h or 24h
        hourly_point_spacing: 76
        hourly_icon_size: 32 # better to set 16, 32 or 64 for better quality
        icon_smoothing: true # should be true for smoother icon or false for sharper icon if using 16, 32 or 64 for hourly_icon_size
        temp_line_width: 3 # can be 0 to hide the temperature line
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "\u26a1 Offline"
        label_workspace_btn: ""
        label_workspace_active_btn: ""
        label_workspace_populated_btn: ""
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false
        hide_if_offline: false
        animation: true
  # weather:
  #   type: "yasb.weather.WeatherWidget"
  #   options:
  #     label: "<span>{icon}</span> {temp}"
  #     label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
  #     api_key: '24b6c2cda6d84066b0304531241908'
  #     update_interval: 600 #Update interval in seconds, Min 600
  #     hide_decimal: true
  #     location: "Dhaka"
  #     units: "imperial"
  #     callbacks:
  #       on_left: "toggle_card"
  #     icons:
  #       sunnyDay: "\udb81\udd99"
  #       clearNight: "\ue3c2"
  #       cloudyDay: "\ue21d"
  #       cloudyNight: "\ue226"
  #       rainyDay: "\ue371"
  #       rainyNight: "\ue371"
  #       snowyIcyDay: "\udb81\udf17"
  #       snowyIcyNight: "\udb81\udf17"
  #       blizzardDay: "\udb81\udd99"
  #       default: "\udb81\udd99"
  #     weather_card:
  #       blur: True
  #       round_corners: True
  #       round_corners_type: "normal"
  #       border_color: "#45475a"
  #       alignment: "right"
  #       direction: "down"
  #       distance: 6
  #       icon_size: 48
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" 
        - "\uf026"
        - "\uf027" 
        - "\uf027"  
        - "\uf028"
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: 'normal'
        border_color: '#45475a'
        alignment: 'right'
        direction: 'down'
        distance: 6
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 250
      button_row: 3
      buttons:
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        sleep: ["\udb82\udd04","Sleep"]
        lock: ["\uf023","Lock"]
        cancel: ["\udb81\udf3a","Cancel"]
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 5
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon} </span> {device_name}"
      label_alt: "{device_name}"
      label_no_device: "No devices"
      label_device_separator: " | "
      max_length: 100
      max_length_ellipsis: "..."
      icons: 
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\uf293"
      device_aliases:
        - name: "T5.0"
          alias: "\uf025"
      callbacks:
        on_left: "toggle_label"
        on_right: "exec bluetoothctl"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
      status_icons:
        icon_charging: "\udb85\udc0b"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\udb80\udc79"
      status_thresholds:
        critical: 10
        low: 50
        medium: 75
        high: 85
        full: 100
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][name]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 18
      max_length: 32
      max_length_ellipsis: "..."
      monitor_exclusive: false 
      rewrite:
      # Strip trailing “.exe” (case-insensitive) and lowercase:
      - pattern: "^(.+?)\\.exe$"
        replacement: "\\1"
        case: lower

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
        duration: 800
        type: "fadeInOut"
      tooltip: true
      monitor_exclusive: true
      ignore_apps:
        processes: []
        titles: ["Command Palette"]
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udfd2</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: ""
      label_expanded: ""
      label_position: "left"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: false
      show_battery: false
      show_volume: false
      show_network: false
      show_volume: false
      show_network: false
      container_padding:
          left: 0
          top: 0
          right: 0
          bottom: 0
      btn_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_strength}% {wifi_name}"
      label_alt: "<span>{wifi_icon}</span> {wifi_name} {wifi_strength}%"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span> {wifi_name}"
      ethernet_icon: "\uf108"
      update_interval: 5000
      callbacks:
        on_left: "exec quick_settings"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      wifi_icons: [
        "\udb82\udd2e",  # Icon for 0% strength
        "\udb82\udd1f",  # Icon for 1-20% strength
        "\udb82\udd22",  # Icon for 21-40% strength
        "\udb82\udd25",  # Icon for 41-80% strength
        "\udb82\udd28"   # Icon for 81-100% strength
      ]
  windows_workspaces:
    type: "yasb.windows_desktops.WorkspaceWidget"
    options:
      label_workspace_active_btn: "\uf108 {name}"
      label_workspace_btn: "\uf111"
      btn_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
