gui:
  skipDiscardChangeWarning: true
  parseEmoji: true
  theme:
    activeBorderColor:
      - "#ee99a0"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#ee99a0"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"
  nerdFontsVersion: "3"
  showFileIcons: true
  authorColors:
    "*": "#b7bdf8"
promptToReturnFromSubprocess: false
notARepository: 'skip'
os:
  openLink: '"/mnt/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe" {{link}}'
